# Generated by Django 5.2.1 on 2025-05-24 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchhistory",
            name="session_key",
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_histories",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
